version: '2.1'

services:
  users-db:
    container_name: users-db
    build: ./db
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=wxx1512
    healthcheck:
      test: exit 0

  users-service:
    container_name: learning_flask
    build: ./
    ports:
      - 5001:5000
    expose:
      - '5000'
    command: gunicorn -b 0.0.0.0:5000 manage:app
    environment:
      - DATABASE_TEST_URL=mysql+pymysql://root:wxx1512@users-db:3306/learning_flask
      - DATABASE_URL=mysql+pymysql://root:wxx1512@users-db:3306/tdd_flask_prod
      - APP_SETTINGS=config.production.Config
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      users-service:
        condition: service_started
    links:
      - users-service